name: CI

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install vcpkg
        run: |
          git clone https://github.com/microsoft/vcpkg
          .\vcpkg\bootstrap-vcpkg.bat

      - name: Create vcpkg cache directory
        run: |
          mkdir "${{ github.workspace }}/vcpkgcache"

      - name: Install dependencies
        run: |
          .\vcpkg\vcpkg.exe install --feature-flags=binarycaching,manifests
        env:
          VCPKG_DEFAULT_BINARY_CACHE: "${{ github.workspace }}/vcpkgcache"
          VCPKG_FEATURE_FLAGS: "manifests,versions"

      - name: Create Build Directory
        run: |
          md cmake-build-debug

      - name: Configure CMake
        run: |
          cd cmake-build-debug
          cmake ..
        env:
          VCPKG_TOOLCHAIN_FILE: ${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake

      - name: Build Project
        run: |
          cd cmake-build-debug
          cmake --build . --config Debug