name: CI

on: [push, pull_request]

jobs:
  build-and-test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - name: Setup environment
        run: |
          git clone https://github.com/microsoft/vcpkg
          if [[ "${{ runner.os }}" == "Windows" ]]; then 
              .\vcpkg\bootstrap-vcpkg.bat
              echo "VCPKG_TARGET_TRIPLET=x64-windows" >> $GITHUB_ENV
          else
              ./vcpkg/bootstrap-vcpkg.sh
              echo "VCPKG_TARGET_TRIPLET=x64-linux" >> $GITHUB_ENV
          fi

      - name: Create vcpkg cache directory
        run: mkdir -p "${{ github.workspace }}/vcpkgcache"

      - name: Install dependencies
        run: |
          if [[ "${{ runner.os }}" == "Windows" ]]; then 
            ./vcpkg/vcpkg install --feature-flags=binarycaching,manifests
          else
            # remove incompatible features before install
            sed -i '/imgui/d' vcpkg.json
            vcpkg install --feature-flags=binarycaching,manifests
          fi
        env:
          VCPKG_DEFAULT_BINARY_CACHE: "${{ github.workspace }}/vcpkgcache"
          VCPKG_FEATURE_FLAGS: "manifests,versions"

      - name: Create Build Directory
        run: mkdir cmake-build-debug

      - name: Configure CMake
        run: |
          cd cmake-build-debug
          cmake .. -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake

      - name: Build Project
        run: |
          cd cmake-build-debug
          cmake --build . --config Debug