name: CI

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install vcpkg
        run: |
          git clone https://github.com/microsoft/vcpkg
          cd vcpkg
          bootstrap-vcpkg.bat

      - name: Install dependencies
        env:
          VCPKG_DEFAULT_BINARY_CACHE: ${{ github.workspace }}/.vcpkgcache
          VCPKG_FEATURE_FLAGS: "manifests,versions"
        run: |
          .\vcpkg\vcpkg install --feature-flags=binarycaching,manifests

      - name: Create Build Directory
        run: |
          md cmake-build-debug

      - name: Configure CMake
        run: |
          cd cmake-build-debug
          cmake ..

      - name: Build Project
        run: |
          cd cmake-build-debug
          cmake --build . --config Debug