name: CI

on: [push, pull_request]

jobs:
  build-and-test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - name: Configurar ambiente
        shell: bash
        run: |
          git clone https://github.com/microsoft/vcpkg
          if [[ "${{ runner.os }}" == "Windows" ]]; then 
              ./vcpkg/bootstrap-vcpkg.bat
              echo "VCPKG_TARGET_TRIPLET=x64-windows" >> $GITHUB_ENV
          else
              ./vcpkg/bootstrap-vcpkg.sh
              echo "VCPKG_TARGET_TRIPLET=x64-linux" >> $GITHUB_ENV
          fi

      - name: Configurar Dependiencias
        shell: bash
        run: |
          if [[ "${{ runner.os }}" == "Windows" ]]; then
              CONFIG_BLOCK='{ "name" : "imgui", "features" : [ "glfw-binding", "opengl3-binding", "dx11-binding", "win32-binding", "docking-experimental" ], "$comment" : "..." }'
          else
              CONFIG_BLOCK='{ "name" : "imgui", "features" : [ "glfw-binding", "opengl3-binding", "docking-experimental" ], "$comment" : "..." }'
          fi

          sed "s|{ \"name\" : \"imgui\" .*}|${CONFIG_BLOCK}|" vcpkg.json > temp.json && mv temp.json vcpkg.json

      - name: Instalar dependências do Ubuntu
        if: runner.os == 'Linux'
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get install -y libxmu-dev libxi-dev libgl-dev

      - name: Criar diretório de cache vcpkg
        run: mkdir -p "${{ github.workspace }}/vcpkgcache"

      - name: Instalar dependências
        shell: bash
        run: |
          ./vcpkg/vcpkg install --feature-flags=binarycaching,manifests
        env:
          VCPKG_DEFAULT_BINARY_CACHE: "${{ github.workspace }}/vcpkgcache"
          VCPKG_FEATURE_FLAGS: "manifests,versions"

      - name: Criar diretório de construção
        shell: bash
        run: mkdir cmake-build-debug

      - name: Configurar CMake
        shell: bash
        run: |
          cd cmake-build-debug
          cmake .. -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake

      - name: Construir projeto
        shell: bash
        run: |
          cd cmake-build-debug
          cmake --build . --config Debug